[tool.poetry]
name = "bitchai-testing"
version = "0.1.0"
description = ""
authors = ["Ata <ataonat00@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
llama-index = "^0.10.36"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
